### ISSUE TITLE
Fatal erreur dans la page emprunt

### ISSUE THREAD

**Issue by smlacombe** [mdesharnais/mediatheque#16]
Lorsque que j'entre un no de référence ou un texte quelconque dans le champ "no de référence" et je clique sur le plus, j'obtiens l'erreur suivante:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'exemplaires_medias.mediaID' in 'on clause'' in /opt/lampp/htdocs/mediatheque/php/getMedia.php:18 Stack trace: #0 /opt/lampp/htdocs/mediatheque/php/getMedia.php(18): PDOStatement->execute() #1 {main} thrown in /opt/lampp/htdocs/mediatheque/php/getMedia.php on line 18

**Comment by xeph** [comment]
as tu executer la base de donnees depuis lajout de la nouvelle table?

**Comment by smlacombe** [comment]
Oui j'ai exécuter la base de données cet après midi et constaté l'erreur.

**Comment by xeph** [comment]
qqn avais changer la colonne mediaID pour exID dans exemplaires_medias c pour cela que sa ne fonctionnais plus
