### ISSUE TITLE
Fatal erreur dans la page retour

### ISSUE THREAD

**Issue by smlacombe** [mdesharnais/mediatheque#17]
Lorsque que je marque un no de référence et que je clique sur le plus j'obtiens l'erreur suivante:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'exemplaires_medias.mediaID' in 'on clause'' in /opt/lampp/htdocs/mediatheque/php/getMedia.php:18 Stack trace: #0 /opt/lampp/htdocs/mediatheque/php/getMedia.php(18): PDOStatement->execute() #1 {main} thrown in /opt/lampp/htdocs/mediatheque/php/getMedia.php on line 18

**Comment by xeph** [comment]
qqn avais changer la colonne mediaID pour exID dans exemplaires_medias c pour cela que sa ne fonctionnais plus
