### ISSUE TITLE
Problème de droits de mofication pour le formulaire de détails des médias

### ISSUE THREAD

**Issue by smlacombe** [mdesharnais/mediatheque#18]
Lorsque déconnecté, j'ai pu aller visionner un média par l'intermédiaire des résultats de recherche. J'ai constaté que je pouvais supprimer des chansons aux médias. Je pense qu'il faudrait interdire cette opération pour un visiteur.

**Comment by mdesharnais** [comment]
C'est tout à fait vrai, mais cela entre, à mon avis, dans le domaine de la programmation. Tu pourras d'ailleurs remarquer que toute la programmation qui touche les second et troisièmes niveaux de détails est à faire.

Je crois que nous pouvons laisser ça à ceux qui reprendront le projet à l'automne prochain.

PS: J'ai montré la page à Marie-Paule et elle dit que ce qui a été fait jusqu'à présent est suffisant pour la présentation.
