### ISSUE TITLE
Ajout d'un lien vers le média sur son image

### ISSUE THREAD

**Issue by mdesharnais** [mdesharnais/mediatheque#2]
Dans les résultats de recherche, il faudrait que nous puissions cliquer sur une image pour consulter les détails du média. À l'heure actuelle, nous devons obligatoirement cliquer sur le titre...

**Comment by smlacombe** [comment]
Bon, j'ai ajouté la possibilité de cliquer sur l'image du média pour se rendre aux détails d'un média.
