### ISSUE TITLE
Possibilité de visionner un média en lecture seule

### ISSUE THREAD

**Issue by smlacombe** [mdesharnais/mediatheque#4]
Martin, tu m'avais dit que le lien vers les détails d'un média dans les résultats de recherche amènerait vers une page de visionnement en lecture seule des détails du média. Or actuellement, si je veux faire cela, ta page "media" me donne l'erreur suivante:
«Vous ne disposez pas des droits suffisant pour accéder à cette page.»

Pourquoi devrions-nous être connecté si on veut visionner les détails?

**Comment by mdesharnais** [comment]
C'est parce que la fonction de validation des droits ne fait aucun 
traitement et retourne toujours la même valeur:
- TRUE si l'on est connecté
- FALSE si l'on est un visiteur

Dans le vrai système, il faudrait simplement dire que le visiteur ait les 
droits en lecture seule sur cette section.

Martin Desharnais
martin.desharnais@gmail.com

**Comment by mdesharnais** [comment]
J'ai ajouté une validation manuelle dans la méthode $application->currentUser->haveRights() afin que les visiteurs aient un accès aux détails d'un média en lecture seule.
