### ISSUE TITLE
Emprunt - plusieurs choses à modifier

### ISSUE THREAD

**Issue by mdesharnais** [mdesharnais/mediatheque#6]
Il y a plusieurs petits détails qu'il faudrait régler dans cette page :
- Modification label du champs « Utilisateur » en quelque chose d'autre (e.g. ID, Matricule, Nom, etc.)
- Un click sur le bouton « Afficher » à coté de l'utilisateur ne fait rien, j'ai tenté de mettre un ID et un matricule.
- Les dates sont en anglais -> utiliser le format ISO (YYYY-MM-DD).
- Les dates sont dans n'importe quel ordre.
- Modification label du champs « Media » en quelque chose d'autre (e.g. ID, Numéro de référence, titre, etc.)
- Un click sur le bouton « + » à coté de du média ne fait rien, j'ai tenté de mettre un ID.
- Un click sur le bouton « + » à coté de du média ne fait rien, j'ai tenté de mettre un ID.
- Englober les -label- -input- dans des -p- et ne pas utiliser de -br-.

**Comment by xeph** [comment]
meme chose que pour retour sauf que les dates ne sont pas dans nimporte quel ordre si tu regarde bien entk pas sur mon ordi

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 _|      _|                                              _|_|                    _|  
 _|_|  _|_|    _|_|_|  _|  _|_|    _|_|_|              _|    _|  _|_|_|      _|_|_|  _|  _|_|    _|_|  
 _|  _|  _|  _|    _|  _|_|      _|        _|_|_|_|_|  _|_|_|_|  _|    _|  _|    _|  _|_|      _|_|_|_|  
 _|      _|  _|    _|  _|        _|                    _|    _|  _|    _|  _|    _|  _|        _|  
 _|      _|    _|_|_|  _|          _|_|_|              _|    _|  _|    _|    _|_|_|  _|          _|_|_|

**Comment by mdesharnais** [comment]
C'est vrai, à bien y regarder, elles sont dans le bon ordre. Je n'avais pas remarquer que l'année changait au milieu ;)
